### ISSUE TITLE
[FEA] Support JITting and Linking LTOIR from cuda source inputs

### ISSUE THREAD

**Issue by isVoid** [NVIDIA/numba-cuda#45]
**Is your feature request related to a problem? Please describe.**
After Pynvjitlink is introduced into `Numba-CUDA`, I would like to be able to jit cuda source files into LTOIR and link it with nvjitlink. This basically requires the linker `lto` flag to be respected by the jit and linker machinery.

**Describe the solution you'd like**
Add `lto` flag to `nvrtc.compile`, and add `-dlto` flag to compile option when set. In the `Linker` class, use `add_ltoir` in `add_cu` when `self.lto` is set.

**Comment by isVoid** [comment]
As a follow up to this PR - it would be helpful to support [`-ptx`](https://docs.nvidia.com/cuda/nvjitlink/index.html#supported-link-options) flag for nvjitlink to emit the PTX under LTOIR linkage, given `NUMBA_DUMP_ASSEMBLY` is set. This makes sure that `Numba-CUDA` shows the LTO-ed PTX and is more useful in debugging optimization related issues.

**Comment by gmarkall** [comment]
I think this was fixed by #62 - is that correct, @isVoid?
