### ISSUE TITLE
local build guidance is missing

### ISSUE THREAD

**Issue by dlee992** [NVIDIA/numba-cuda#7]
Ha, when I ran with numba-cuda, it reports 
```python
ImportError: cannot import name '_extras' from 'numba.cuda.cudadrv' (/home/dli/numba-cuda/numba_cuda/numba/cuda/cudadrv/__init__.py)
```

Then I built this with `CMakeLists.txt`, it reports
```
CMake Error at CMakeLists.txt:16 (install):
  install FILES given no DESTINATION!
```
looks like need to export `SKBUILD_PROJECT_VERSION` and `SKBUILD_PLATLIB_DIR`.

Then I set it in CMakeLists
```
set(SKBUILD_PROJECT_VERSION "1.0.0") # Example version, adjust as necessary
set(SKBUILD_PLATLIB_DIR "/home/dli/numba-cuda/build") # Example path, adjust as necessary
```

Building is fine now.

But when I reran the python script, still the same error. I need to manually move the `_extra.so` to `numba_cuda/numba/cuda/cudadrv`. 

Finally, everything "works".

**Comment by dlee992** [comment]
should be fixed by https://github.com/NVIDIA/numba-cuda/pull/5?

**Comment by gmarkall** [comment]
Yes, it should be fixed by that PR. I'm just waiting for CI to start working again to test it before I merge it.

**Comment by gmarkall** [comment]
I think this should be fixed now - the `_extras` module no longer exists, nor does the CMake-based build system.
